name: 🚀 Deploy a InfinityFree via FTP

on:
  push:
    branches:
      - main  # o el branch que uses para producción

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📂 Checkout repo
        uses: actions/checkout@v4

      - name: 🚀 Deploy to InfinityFree
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/
          exclude: |
            */.git
            */.github
            **/README.md
